INSERT INTO USERS(USERNAME,PASSWORD,ROLE) VALUES ('Admin','admin123','ADMIN');
INSERT INTO USERS(USERNAME,PASSWORD,ROLE) VALUES ('Pero','pero123','USER');

INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Frank+Ocean/Blonde','Blonde','Frank Ocean','https://lastfm.freetls.fastly.net/i/u/300x300/d204f358ae4063561370b9dc7c0cb8ca.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('High5/SCHENGENGANG','SCHENGENGANG','High5','https://lastfm.freetls.fastly.net/i/u/300x300/241fe1fe3a8086c1cdcf5d61d60f123c.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Kid+Cudi/Man+on+the+Moon+III:+The+Chosen','Man on the Moon III: The Chosen','Kid Cudi','https://lastfm.freetls.fastly.net/i/u/300x300/ef273ffb2a9fecee0cdf83a1e8e00346.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Arctic+Monkeys/AM','AM','Arctic Monkeys','https://lastfm.freetls.fastly.net/i/u/300x300/f579e414e20f40969185e41182d72472.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('The+Weeknd/After+Hours','After Hours','The Weeknd','https://lastfm.freetls.fastly.net/i/u/300x300/7d957bd27dd562bee7aaa89eafa0bbe6.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Kendrick+Lamar/DAMN.','DAMN.','Kendrick Lamar','https://lastfm.freetls.fastly.net/i/u/300x300/48a06b6d023e74d0179939e449683d7b.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Pink+Floyd/The+Dark+Side+Of+The+Moon','The Dark Side of the Moon','Pink Floyd','https://lastfm.freetls.fastly.net/i/u/300x300/d4bdd038cacbec705e269edb0fd38419.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Gorillaz/Demon+Days','Demon Days','Gorillaz','https://lastfm.freetls.fastly.net/i/u/300x300/271483e955d2b255160f3361a7f5fb78.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Kanye+West/Graduation','Graduation','Kanye West','https://lastfm.freetls.fastly.net/i/u/300x300/8ddd1959a2bef460a5149b3e0cf5e18a.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Playboi+Carti/Whole+Lotta+Red','Whole Lotta Red','Playboi Carti','https://lastfm.freetls.fastly.net/i/u/300x300/0db2bb3f8dcebb4279db97dc7608d090.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Daft+Punk/Random+Access+Memories','Random Access Memories','Daft Punk','https://lastfm.freetls.fastly.net/i/u/300x300/11dd7e48a1f042c688bf54985f01d088.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('High5/BackStageBoys','BackStageBoys','High5','https://lastfm.freetls.fastly.net/i/u/300x300/8a189b3399367ef25dbde75ed5b31e9f.png');

INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,1,'LISTEN_LATER');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,2,'LIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,3,'DISLIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,4,'LIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,5,'LIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,6,'LIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,7,'LIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,8,'LIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,9,'LIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,10,'LIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,11,'LIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,12,'LIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (2,1,'LISTEN_LATER');