CREATE TABLE USERS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    ROLE ENUM('USER', 'ADMIN') DEFAULT 'USER',
    STATUS ENUM('ACTIVE', 'DEACTIVATED', 'SUSPENDED') DEFAULT 'ACTIVE',
    DATE_CREATED DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (ID)
);

CREATE TABLE ALBUMS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    FULL_NAME VARCHAR(255) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL,
    ARTIST VARCHAR(100) NOT NULL,
    IMG_URL VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UC_FULL_NAME UNIQUE (FULL_NAME)
);

CREATE TABLE SAVED_ALBUMS (
    USER_ID BIGINT,
    ALBUM_ID BIGINT,
    ACTION ENUM('LISTEN_LATER', 'LIKE', 'DISLIKE'),
    DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, ALBUM_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (ALBUM_ID) REFERENCES ALBUMS(ID)
);

CREATE TABLE FRIENDS (
     ID BIGINT GENERATED ALWAYS AS IDENTITY,
     USER1_ID BIGINT NOT NULL,
     USER2_ID BIGINT NOT NULL,
     TIMESTAMP_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     PRIMARY KEY (ID),
     FOREIGN KEY (USER1_ID) REFERENCES USERS(ID),
     FOREIGN KEY (USER2_ID) REFERENCES USERS(ID)
);

CREATE TABLE INVITES (
     ID BIGINT GENERATED ALWAYS AS IDENTITY,
     SENDER_ID BIGINT NOT NULL,
     RECEIVER_ID BIGINT NOT NULL,
     INVITE_TYPE ENUM('FRIEND_REQUEST', 'ALBUM_RECOMMENDATION') NOT NULL,
     ALBUM_ID BIGINT,
     MESSAGE VARCHAR(255),
     TIMESTAMP_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     PRIMARY KEY (ID),
     FOREIGN KEY (SENDER_ID) REFERENCES USERS(ID),
     FOREIGN KEY (RECEIVER_ID) REFERENCES USERS(ID),
     FOREIGN KEY (ALBUM_ID) REFERENCES ALBUMS(ID),
     CHECK (
         (INVITE_TYPE = 'ALBUM_RECOMMENDATION' AND ALBUM_ID IS NOT NULL) OR
         (INVITE_TYPE = 'FRIEND_REQUEST')
         )
);


INSERT INTO USERS(USERNAME,PASSWORD,ROLE) VALUES ('Matija','matija123','ADMIN');
INSERT INTO USERS(USERNAME,PASSWORD,ROLE) VALUES ('Pero','pero123','USER');
INSERT INTO USERS(USERNAME,PASSWORD,ROLE) VALUES ('Ana','ana123','USER');
INSERT INTO USERS(USERNAME,PASSWORD,ROLE) VALUES ('Marko','marko123','USER');

INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Frank+Ocean/Blonde','Blonde','Frank Ocean','https://lastfm.freetls.fastly.net/i/u/300x300/d204f358ae4063561370b9dc7c0cb8ca.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('High5/SCHENGENGANG','SCHENGENGANG','High5','https://lastfm.freetls.fastly.net/i/u/300x300/241fe1fe3a8086c1cdcf5d61d60f123c.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Kid+Cudi/Man+on+the+Moon+III:+The+Chosen','Man on the Moon III: The Chosen','Kid Cudi','https://lastfm.freetls.fastly.net/i/u/300x300/ef273ffb2a9fecee0cdf83a1e8e00346.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Arctic+Monkeys/AM','AM','Arctic Monkeys','https://lastfm.freetls.fastly.net/i/u/300x300/f579e414e20f40969185e41182d72472.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('The+Weeknd/After+Hours','After Hours','The Weeknd','https://lastfm.freetls.fastly.net/i/u/300x300/7d957bd27dd562bee7aaa89eafa0bbe6.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Kendrick+Lamar/DAMN.','DAMN.','Kendrick Lamar','https://lastfm.freetls.fastly.net/i/u/300x300/48a06b6d023e74d0179939e449683d7b.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Pink+Floyd/The+Dark+Side+Of+The+Moon','The Dark Side of the Moon','Pink Floyd','https://lastfm.freetls.fastly.net/i/u/300x300/d4bdd038cacbec705e269edb0fd38419.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Gorillaz/Demon+Days','Demon Days','Gorillaz','https://lastfm.freetls.fastly.net/i/u/300x300/271483e955d2b255160f3361a7f5fb78.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Kanye+West/Graduation','Graduation','Kanye West','https://lastfm.freetls.fastly.net/i/u/300x300/8ddd1959a2bef460a5149b3e0cf5e18a.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Playboi+Carti/Whole+Lotta+Red','Whole Lotta Red','Playboi Carti','https://lastfm.freetls.fastly.net/i/u/300x300/0db2bb3f8dcebb4279db97dc7608d090.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Daft+Punk/Random+Access+Memories','Random Access Memories','Daft Punk','https://lastfm.freetls.fastly.net/i/u/300x300/11dd7e48a1f042c688bf54985f01d088.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('High5/BackStageBoys','BackStageBoys','High5','https://lastfm.freetls.fastly.net/i/u/300x300/8a189b3399367ef25dbde75ed5b31e9f.png');
INSERT INTO ALBUMS(FULL_NAME,NAME,ARTIST,IMG_URL) VALUES ('Kanye+West/Yandhi','Yandhi','Kanye West','https://lastfm.freetls.fastly.net/i/u/300x300/57c1731b0f18c6f288e30a6c3ad42eb6.jpg');

INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,1,'LISTEN_LATER');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,2,'LISTEN_LATER');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,3,'LISTEN_LATER');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,4,'LIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,5,'LIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,6,'LIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,7,'LIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,8,'LIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,9,'LIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,10,'DISLIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,11,'DISLIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,12,'DISLIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (1,13,'LIKE');
INSERT INTO SAVED_ALBUMS(USER_ID,ALBUM_ID,ACTION) VALUES (2,5,'LISTEN_LATER');

INSERT INTO FRIENDS(USER1_ID, USER2_ID) VALUES (1,2);

INSERT INTO INVITES(SENDER_ID,RECEIVER_ID,INVITE_TYPE) VALUES (2,1,'FRIEND_REQUEST');
INSERT INTO INVITES(SENDER_ID,RECEIVER_ID,INVITE_TYPE,ALBUM_ID,MESSAGE) VALUES (2,1,'ALBUM_RECOMMENDATION',1,'Check this album out!');
