CREATE TABLE USERS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    ROLE ENUM('USER', 'ADMIN') DEFAULT 'USER',
    STATUS ENUM('ACTIVE', 'DEACTIVATED', 'SUSPENDED') DEFAULT 'ACTIVE',
    DATE_CREATED DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (ID)
);

CREATE TABLE ALBUMS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    FULL_NAME VARCHAR(255) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL,
    ARTIST VARCHAR(100) NOT NULL,
    IMG_URL VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UC_FULL_NAME UNIQUE (FULL_NAME)
);

CREATE TABLE SAVED_ALBUMS (
    USER_ID BIGINT,
    ALBUM_ID BIGINT,
    ACTION ENUM('LISTEN_LATER', 'LIKE', 'DISLIKE'),
    DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, ALBUM_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (ALBUM_ID) REFERENCES ALBUMS(ID)
);